# Generated by Django 5.0.2 on 2024-02-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_product_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='reels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
