# Generated by Django 5.0.2 on 2024-02-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_photos_product_reels_product_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
